//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generator tool.
//     Created By		: CodeBhagat v1.0
//     Created Date		: 2017/1/13
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWebsite {
    
    public partial class sa106Search {
        
         /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// pnlSearch2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSearch2;
        
        /// <summary>
        /// lblSearchPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSearchPanel;
        
        /// <summary>
        /// imgExpand control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton imgExpand;
        
        /// <summary>
        /// pnlSearch1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSearch1;
        
        /// <summary>
        /// lbtnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtnSearch;
        
        /// <summary>
        /// btnClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnClear;
        
        /// <summary>
        /// cpeDemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeDemo;


		protected System.Web.UI.WebControls.TextBox txtgkey;
		protected System.Web.UI.WebControls.TextBox txtorddate;
		protected System.Web.UI.WebControls.TextBox txtmr200gkey;
		protected System.Web.UI.WebControls.TextBox txtissuedate;
		protected System.Web.UI.WebControls.TextBox txtpono;
		protected System.Web.UI.WebControls.TextBox txtsalesno;
		protected System.Web.UI.WebControls.TextBox txtreturnno;
		protected System.Web.UI.WebControls.TextBox txtreturndate;
		protected System.Web.UI.WebControls.TextBox txtdeliveryno;
		protected System.Web.UI.WebControls.TextBox txtrettype;
		protected System.Web.UI.WebControls.TextBox txtxtype;
		protected System.Web.UI.WebControls.TextBox txtba205gkey;
		protected System.Web.UI.WebControls.TextBox txtpickupdate;
		protected System.Web.UI.WebControls.TextBox txtcanceldate;
		protected System.Web.UI.WebControls.TextBox txtba100gkey;
		protected System.Web.UI.WebControls.TextBox txtba102gkey;
		protected System.Web.UI.WebControls.TextBox txtba103gkey;
		protected System.Web.UI.WebControls.TextBox txtba119gkey;
		protected System.Web.UI.WebControls.TextBox txtba118gkey;
		protected System.Web.UI.WebControls.TextBox txtba121gkey;
		protected System.Web.UI.WebControls.TextBox txtba104gkey;
		protected System.Web.UI.WebControls.TextBox txtba209gkey;
		protected System.Web.UI.WebControls.TextBox txtreturnamt;
		protected System.Web.UI.WebControls.TextBox txtcanadaamt;
		protected System.Web.UI.WebControls.TextBox txtfreightamt;
		protected System.Web.UI.WebControls.TextBox txtproceamt;
		protected System.Web.UI.WebControls.TextBox txtinsuredamt;
		protected System.Web.UI.WebControls.TextBox txtpickupamt;
		protected System.Web.UI.WebControls.TextBox txtdiscountamt;
		protected System.Web.UI.WebControls.TextBox txtvouchersamt;
		protected System.Web.UI.WebControls.TextBox txtreservatamt;
		protected System.Web.UI.WebControls.TextBox txtactivityamt;
		protected System.Web.UI.WebControls.TextBox txttotalfreight;
		protected System.Web.UI.WebControls.TextBox txttotaltreatment;
		protected System.Web.UI.WebControls.TextBox txttotalinsurance;
		protected System.Web.UI.WebControls.TextBox txttotalamt;
		protected System.Web.UI.WebControls.TextBox txtpairs;
		protected System.Web.UI.WebControls.TextBox txtremark;
		protected System.Web.UI.WebControls.TextBox txtba005gkey;
		protected System.Web.UI.WebControls.TextBox txtmodifydate;
		protected System.Web.UI.WebControls.TextBox txtrevisedate;
		protected System.Web.UI.WebControls.TextBox txtapprove;
		protected System.Web.UI.WebControls.TextBox txtaes101gkey;
		protected System.Web.UI.WebControls.TextBox txtses101gkey;
		protected System.Web.UI.WebControls.TextBox txtes101gkey;
		protected System.Web.UI.WebControls.TextBox txtreplication_create;
		protected System.Web.UI.WebControls.TextBox txtreplication_update;
		protected System.Web.UI.WebControls.TextBox txtrownum;
		protected System.Web.UI.WebControls.TextBox txtaddproceamt;
		protected System.Web.UI.WebControls.TextBox txtlossproceamt;
		protected System.Web.UI.WebControls.TextBox txtvirementamt;
		protected System.Web.UI.WebControls.TextBox txtba040gkey;
		protected System.Web.UI.WebControls.TextBox txtba040gkey1;
		protected System.Web.UI.WebControls.TextBox txtreceivabledate;
		protected System.Web.UI.WebControls.TextBox txtreceivableamt;
		protected System.Web.UI.WebControls.TextBox txtvirementdate;
		protected System.Web.UI.WebControls.TextBox txtsalesamt;
		protected System.Web.UI.WebControls.TextBox txtcollchk;
		protected System.Web.UI.WebControls.TextBox txtpayfreight;
		protected System.Web.UI.WebControls.TextBox txtstrchk;
		protected System.Web.UI.WebControls.TextBox txtnoamount;
		protected System.Web.UI.WebControls.TextBox txttotalamount;
		protected System.Web.UI.WebControls.TextBox txtba101gkey;
		protected System.Web.UI.WebControls.TextBox txtremittancedate;
		protected System.Web.UI.WebControls.TextBox txtremittancetime;
	}
}
